"""Vanilla existence manifests from `Millennium-Dawn/tools/validation/`.

These committed files answer "does X exist in vanilla?" without a HOI4 install
(CI and agents with no `HOI4_PATH` configured). They are regenerated by the mod
repo's `refresh_vanilla_data.py` after a version bump. Each is a `#`-comment
header followed by one sorted entry per line.

Only `vanilla_sprites.txt` is consumed here today; the loader is shared so the
other manifests (`vanilla_paths`, `vanilla_defines`, `vanilla_gui_files`) can be
added without duplicating the parse.
"""

from __future__ import annotations

from pathlib import Path
from typing import FrozenSet, Optional


def load_manifest(mod_root: Path, filename: str) -> Optional[FrozenSet[str]]:
    """Return the manifest entries as a set, or None if the manifest is absent.

    Comment lines (leading `#`) and blank lines are skipped; entries are
    stripped. Absence is reported as None (not an empty set) so callers can
    distinguish "no manifest" from "empty manifest".
    """
    path = mod_root / "tools" / "validation" / filename
    if not path.is_file():
        return None
    entries: set[str] = set()
    try:
        with open(path, "r", encoding="utf-8") as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith("#"):
                    continue
                entries.add(line)
    except OSError:
        return None
    return frozenset(entries)


def load_sprite_manifest(mod_root: Path) -> Optional[FrozenSet[str]]:
    """Load `vanilla_sprites.txt`, or None when it is missing/unreadable."""
    return load_manifest(mod_root, "vanilla_sprites.txt")
